esgi_user:
    resource: "@EsgiUserBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml

esgi_blog:
    resource: "@EsgiBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"