# Esgi/BlogBundle/Resources/config/admin.yml
services:
    sonata.admin.posts:
        class: Esgi\BlogBundle\Admin\PostAdmin
        tags:
            -  name: sonata.admin
               manager_type: orm
               group: "Posts"
               label: "Posts"
        arguments:
            - ~
            - Esgi\BlogBundle\Entity\Posts
            - ~
        calls:
            - [ setTranslationDomain, [EsgiBlogBundle]]

    sonata.admin.categories:
        class: Esgi\BlogBundle\Admin\CategoriesAdmin
        tags:
            -  name: sonata.admin
               manager_type: orm
               group: "Categories"
               label: "Categories"
        arguments:
            - ~
            - Esgi\BlogBundle\Entity\Categories
            - ~
        calls:
            - [ setTranslationDomain, [EsgiBlogBundle]]

    sonata.admin.users:
        class: Esgi\BlogBundle\Admin\UserAdmin
        tags:
            -  name: sonata.admin
               manager_type: orm
               group: "Users"
               label: "Users"
        arguments:
            - ~
            - Esgi\UserBundle\Entity\User
            - ~
        calls:
            - [ setTranslationDomain, [EsgiBlogBundle]]

    sonata.admin.comments:
        class: Esgi\BlogBundle\Admin\CommentAdmin
        tags:
            -  name: sonata.admin
               manager_type: orm
               group: "Comments"
               label: "Comments"
        arguments:
            - ~
            - Esgi\BlogBundle\Entity\Comments
            - ~
        calls:
            - [ setTranslationDomain, [EsgiBlogBundle]]
