# Esgi/BlogBundle/Resources/config/admin.yml
services:
    sonata.admin.post:
        class: Esgi\BlogBundle\Admin\PostAdmin
        tags:
            -  name: sonata.admin
               manager_type: orm
               group: "Posts"
               label: "Actions"
        arguments:
            - ~
            - Esgi\BlogBundle\Entity\Posts
            - ~
        calls:
            - [ setTranslationDomain, [EsgiBlogBundle]]

    sonata.admin.user:
            class: Esgi\BlogBundle\Admin\UserAdmin
            tags:
                -  name: sonata.admin
                   manager_type: orm
                   group: "Users"
                   label: "Actions"
            arguments:
                - ~
                - Esgi\UserBundle\Entity\User
                - ~
            calls:
                - [ setTranslationDomain, [EsgiBlogBundle]]
