# src/Esgi/BlogBundle/Resources/config/routing.yml

esgi_blog_category_show:
    path:     /category/{slug}.{format}
    defaults: { _controller: "EsgiBlogBundle:Category:show", format: html }
    requirements:
        format: html

esgi_blog_post:
    path:     /
    defaults: { _controller: "EsgiBlogBundle:Posts:index" }

esgi_blog_post_show:
    path:     /posts/{slug}.{format}
    defaults: { _controller: "EsgiBlogBundle:Posts:show", format: html }
    requirements:
        format: html

esgi_blog_post_new:
    path:     /new
    defaults: { _controller: "EsgiBlogBundle:Posts:new" }

esgi_blog_post_create:
    path:     /create
    defaults: { _controller: "EsgiBlogBundle:Posts:create" }
    methods:  POST

esgi_blog_post_edit:
    path:     /edit/{id}
    defaults: { _controller: "EsgiBlogBundle:Posts:edit" }
    requirements:
                 id: \d+


esgi_blog_post_update:
    path:     /update/{id}
    defaults: { _controller: "EsgiBlogBundle:Posts:update" }
    requirements:
                 _method: PUT|POST
                 id: \d+


esgi_blog_post_delete:
    path:     /delete/{id}
    defaults: { _controller: "EsgiBlogBundle:Posts:delete" }
    requirements:
                 _method: DELETE|POST
                 id: \d+

esgi_blog_comments:
    path:     /comments
    defaults: { _controller: "EsgiBlogBundle:Comments:index" }

esgi_blog_comments_show:
    path:     /comments/show/{id}
    defaults: { _controller: "EsgiBlogBundle:Comments:show" }
    requirements:
                 id: \d+

esgi_blog_comments_new:
    path:     /comments/new
    defaults: { _controller: "EsgiBlogBundle:Comments:new" }

esgi_blog_comments_create:
    path:     /comments/create
    defaults: { _controller: "EsgiBlogBundle:Comments:create" }
    methods:  POST

esgi_blog_comments_edit:
    path:     /comments/{id}/edit
    defaults: { _controller: "EsgiBlogBundle:Comments:edit" }
    requirements:
                 id: \d+

esgi_blog_comments_update:
    path:     /comments/update/{id}
    defaults: { _controller: "EsgiBlogBundle:Comments:update" }
    requirements:
                 _method: PUT|POST
                 id: \d+

esgi_blog_comments_delete:
    path:     /comments/delete/{id}
    defaults: { _controller: "EsgiBlogBundle:Comments:delete" }
    requirements:
                 _method: DELETE|POST
                 id: \d+
