# src/Esgi/BlogBundle/Resources/config/routing.yml

esgi_blog_post:
    path:     /
    defaults: { _controller: "EsgiBlogBundle:Posts:index" }

esgi_blog_post_show:
    path:     /{id}
    defaults: { _controller: "EsgiBlogBundle:Posts:show" }

esgi_blog_post_new:
    path:     /new
    defaults: { _controller: "EsgiBlogBundle:Posts:new" }

esgi_blog_post_create:
    path:     /create
    defaults: { _controller: "EsgiBlogBundle:Posts:create" }
    methods:  POST

esgi_blog_post_edit:
    path:     /edit/{id}
    defaults: { _controller: "EsgiBlogBundle:Posts:edit" }

esgi_blog_post_update:
    path:     /update/{id}
    defaults: { _controller: "EsgiBlogBundle:Posts:update" }
    methods:  [POST, PUT]

esgi_blog_post_delete:
    path:     /delete/{id}
    defaults: { _controller: "EsgiBlogBundle:Posts:delete" }
    methods:  [POST, DELETE]
