<?php

namespace Esgi\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Get category datas by it's ID joined to User's Entity
     *
     * @return Category
     */
    public function findOneByIdJoinedToUser($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT p, u
            FROM EsgiBlogBundle:Categories p
            JOIN p.user u
            WHERE p.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    /**
     * Get category datas by it's slug joined to User's Entity
     *
     * @return Category
     */
    public function getPostsByCategoryId($categoryId)
    {
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT p, c
            FROM EsgiBlogBundle:Categories c
            JOIN p.post_id p
            WHERE p.post_id = :categoryId'
            )->setParameter('categoryId', $categoryId);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
