<?php

namespace Esgi\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Get category datas by it's ID joined to User's Entity
     *
     * @return Category
     */
    public function findOneByIdJoinedToUser($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT p, u
            FROM EsgiBlogBundle:Categories p
            JOIN p.user u
            WHERE p.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    /**
     * Get category datas by it's slug joined to User's Entity
     *
     * @return Category
     */
    public function findAllWithCount(){
        return $this->getEntityManager()->getRepository('EsgiBlogBundle:Posts')->createQueryBuilder('p')
            ->select('p, c, COUNT(p) AS postCount')
            ->join('p.category', 'c')
            ->groupBy('c.id')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findAllByCategorySlug($categorySlug) {
        $produits = $this->get('Doctrine')
            ->getManager()
            ->getRepository('EsgiBlogBundle:Posts')
            ->findByCategorySlug($categorySlug);

        return $this->render('EsgiBlogBundle:category.html.twig',
            array('posts' =>     $posts,
                'category' =>    $category )
        );
    }
}
