<?php

namespace Esgi\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentsRepository extends EntityRepository
{
    /**
     * Find comments by post id
     *
     * @param $id
     * @return array|\Doctrine\ORM\QueryBuilder
     */
    public function findByPost($id)
    {
        $query = $this->createQueryBuilder('c')
            ->select('c')
            ->leftJoin('c.post', 'p')
            ->addSelect('p');

        $query = $query->add('where', $query->expr()->in('p', ':p'))
            ->setParameter('p', $id)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
