<?php

namespace Esgi\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends EntityRepository
{
    /**
     * Get post datas by it's ID joined to User's Entity
     *
     * @return Post
     */
    public function findOneByIdJoinedToUser($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT p, u
            FROM EsgiBlogBundle:Posts p
            JOIN p.user u
            WHERE p.id = :id'
            )->setParameter('id', $id);

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }

    /**
     * Find posts by categoy id
     *
     * @param $id
     * @return array|\Doctrine\ORM\QueryBuilder
     */
    public function findByCategory($id)
    {
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('p.categories', 'c')
            ->addSelect('c');

        $query = $query->add('where', $query->expr()->in('c', ':c'))
            ->setParameter('c', $id)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
