<?php

namespace Esgi\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostsRepository extends EntityRepository
{
    private $validPostStatus = 'Publié';

    /**
     * Get post datas by it's ID joined to User's Entity.
     *
     * @return Post
     */
    public function findOneByIdJoinedToUser($id)
    {
        $query = $this->getEntityManager()
            ->createQuery('
                SELECT p, u
                FROM EsgiBlogBundle:Posts p
                JOIN p.user u
                WHERE p.id = :id
                AND p.postStatus = :postStatus'
            )
            ->setParameter('id', $id)
            ->setParameter('p.postStatus', $this->validPostStatus)
        ;

        try {
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return;
        }
    }

    /**
     * Get post datas by it's slug joined to User's Entity.
     *
     * @return Post
     */
    public function findOneBySlugJoinedToUser($postSlug)
    {
        $query = $this->getEntityManager()
            ->createQuery('
            SELECT p, u
            FROM EsgiBlogBundle:Posts p
            JOIN p.user u
            WHERE p.postSlug = :postSlug
            AND p.postStatus = :postStatus'
            )
            ->setParameter('postSlug', $postSlug)
            ->setParameter('postStatus', $this->validPostStatus)
        ;

        try {
            /*echo "<pre>".print_r($query->getSingleResult(),true)."</pre>";
            exit;*/
            return $query->getSingleResult();
        } catch (\Doctrine\ORM\NoResultException $e) {
            return;
        }
    }

    /**
     * Find posts by categoy id.
     *
     * @param $id
     *
     * @return array|\Doctrine\ORM\QueryBuilder
     */
    public function findByCategory($id)
    {
        $query = $this->createQueryBuilder('p')
            ->select('p')
            ->leftJoin('p.categories', 'c')
            ->addSelect('c');

        $query = $query->add('where', $query->expr()->in('c', ':c'))
            ->andWhere('p.postStatus = :postStatus')
            ->setParameter('c', $id)
            ->setParameter('postStatus', $this->validPostStatus)
            ->getQuery()
            ->getResult();

        return $query;
    }
}
